### ISSUE TITLE
this ugly :(

### ISSUE THREAD

**Issue by avi-2-avi** [1ns4w/portfolio#3]
this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( this ugly :( 

- Your front bean

**Comment by 1ns4w** [comment]
aguante messi
